/* auto-generated by scripts/vendor-openclaw-runtime-artifact.mjs */
/* eslint-disable */

export type VendoredOpenClawRuntimeArtifactManifest = {
  schemaVersion: 1;
  packageName: "openclaw";
  packageSpec: string;
  version: string;
  sha256: string;
  tarballFile: string;
  builtAt: string;
  gitCommit: string | null;
};

export const VENDORED_OPENCLAW_RUNTIME_ARTIFACT = {
  manifest: {
  "schemaVersion": 1,
  "packageName": "openclaw",
  "packageSpec": "openclaw@2026.4.10",
  "version": "2026.4.10",
  "sha256": "d66766f98948c72a535fd59ee4ff5abaa7efcce6cb79f504f65878efdacb5d65",
  "tarballFile": "openclaw-runtime-2026.4.10.tgz",
  "builtAt": "2026-04-13T19:13:20.558Z",
  "gitCommit": "0f0a192ecbbe2d304d4056b26c47f6b0e71ad84a"
} as const satisfies VendoredOpenClawRuntimeArtifactManifest,
  tarballUrl: new URL("./runtime-artifact/openclaw-runtime-2026.4.10.tgz", import.meta.url),
} as const;
