#!/usr/bin/env tsx
import { readFileSync } from "node:fs";

import {
  CHANNEL_DELIVERY_EVENTS,
  CHANNEL_DELIVERY_STATES,
  CHANNEL_NOTICE_STATES,
  renderChannelDeliveryMermaid,
} from "@/shared/channel-delivery";

const docPath = "docs/channel-delivery-state-machine.md";

const expectedMermaidBlock = [
  "<!-- Generated by scripts/render-channel-delivery-diagram.ts -->",
  "<!-- Source: src/shared/channel-delivery.ts -->",
  "```mermaid",
  renderChannelDeliveryMermaid().trimEnd(),
  "```",
].join("\n");

const doc = readFileSync(docPath, "utf8");
if (!doc.includes(expectedMermaidBlock)) {
  throw new Error(
    `${docPath} is stale. Run: pnpm exec tsx scripts/render-channel-delivery-diagram.ts`,
  );
}

const missing = [
  ...CHANNEL_DELIVERY_STATES,
  ...CHANNEL_NOTICE_STATES,
  ...CHANNEL_DELIVERY_EVENTS,
].filter((value) => !doc.includes(value));

if (missing.length > 0) {
  throw new Error(`${docPath} is missing channel delivery terms: ${missing.join(", ")}`);
}
