#!/usr/bin/env tsx
import { writeFileSync } from "node:fs";
import process from "node:process";

import {
  CHANNEL_DELIVERY_EVENTS,
  CHANNEL_DELIVERY_STATES,
  CHANNEL_NOTICE_STATES,
  renderChannelDeliveryMermaid,
} from "@/shared/channel-delivery";

const outputPath = process.argv[2] ?? "docs/channel-delivery-state-machine.md";
const contents = [
  "# Channel Delivery State Machine",
  "",
  "This document contains the generated state diagram for the shared channel delivery core.",
  "",
  "The source of truth is `src/shared/channel-delivery.ts`; regenerate this file with `pnpm exec tsx scripts/render-channel-delivery-diagram.ts` after changing states or transitions.",
  "",
  "<!-- Generated by scripts/render-channel-delivery-diagram.ts -->",
  "<!-- Source: src/shared/channel-delivery.ts -->",
  "```mermaid",
  renderChannelDeliveryMermaid().trimEnd(),
  "```",
  "",
  "## Terms",
  "",
  `Delivery states: \`${CHANNEL_DELIVERY_STATES.join("`, `")}\`.`,
  "",
  `Notice states: \`${CHANNEL_NOTICE_STATES.join("`, `")}\`.`,
  "",
  `Delivery events: \`${CHANNEL_DELIVERY_EVENTS.join("`, `")}\`.`,
  "",
].join("\n");

writeFileSync(outputPath, contents, "utf8");
